-- This is a placeholder file for directly adding game content that would
-- typically be added in mod format

-- Items -----------------------------------------------------------------------

local Item = require('Systems.Economy.Item')

Item.T1 = {} -- nonsolid
Item.T2 = {} -- solid, raw, inanimate
Item.T3 = {} -- solid, raw, animate
Item.T4 = {} -- solid, processed, elemental
Item.T5 = {} -- solid, processed, constructed
Item.T6 = {} -- solid, processed, constructed, ship-specific

--                       NAME               UNIT MASS   ENERGY-DENSITY
Item.Energy      = Item("Energy Cell",              1,   1.00)
Item.Data        = Item("Data Cube",                1,   0.10)
Item.Information = Item("Info Wafer",               1,   0.12)
Item.WaterIce    = Item("Water Ice",                8,   1.50)
Item.WaterLiquid = Item("Liquid Water",            10,   1.00)
Item.Isotopes    = Item("Radioactive Isotopes",    18,   2.00)
Item.Silicates   = Item("Silicate Ore",             4,   0.02)
Item.Chondrites  = Item("Carboniferous Ore",        7,   0.48)
Item.AluminumOre = Item("Aluminum Ore",             7,   0.10)
Item.IronOre     = Item("Iron Ore",                10,   0.18)
Item.CopperOre   = Item("Copper Ore",              11,   0.24)
Item.PlatinumOre = Item("Platinum Ore",            15,   1.13)
Item.ThoriumOre  = Item("Thorium Ore",             25,   3.50)
Item.Biomass     = Item("Biomass",                  8,   5.00)
Item.Hydrogen    = Item("Hydrogen",                 1,   2.00)
Item.Helium      = Item("Helium",                   1,   0.01)
Item.Lithium     = Item("Lithium",                  1,   0.20)
Item.Beryllium   = Item("Beryllium",                2,   0.30)
Item.Boron       = Item("Boron",                    2,   0.20)
Item.Carbon      = Item("Carbon",                   2,   0.30)
Item.Nitrogen    = Item("Nitrogen",                 1,   0.05)
Item.Oxygen      = Item("Oxygen",                   1,   2.00)
Item.Aluminum    = Item("Aluminum",                 3,   0.80)
Item.Silicon     = Item("Silicon",                  2,   1.00)
Item.Iron        = Item("Iron",                     5,   2.00)
Item.Copper      = Item("Copper",                   5,   2.50)
Item.Silver      = Item("Silver",                   5,   3.00)
Item.Gold        = Item("Gold",                     6,   6.00)
Item.Platinum    = Item("Platinum",                 8,   8.00)
Item.Thorium     = Item("Thorium",                  9,  27.00)
Item.Steel       = Item("Steel",                    7,   4.00)
Item.Petroleum   = Item("Petroleum",                6,   0.90)
Item.Plastic     = Item("Plastic",                  4,   0.90)
Item.Infolytic   = Item("Infolytic Chip",           5,   1.35)
Item.Glassiron   = Item("Glassiron",               12,   1.00)
Item.TranspAlum  = Item("Transparent Aluminum",     7,   1.70)
Item.WasteRad    = Item("Radioactive Waste",       15,   0.50)
Item.Waste       = Item("Waste",                    2,   0.01)
Item.AnodeSludge = Item("Anode Sludge",            10,   0.12)
Item.HullShip    = Item("Ship Hull",            15000, 150.00)
Item.EngineShip  = Item("Ship Engine",            500,  25.00)
Item.WeaponShip  = Item("Ship Weapon",            100,  10.00)

insert(Item.T1, Item.Energy)
insert(Item.T1, Item.Data)
insert(Item.T1, Item.Information)
insert(Item.T2, Item.WaterIce)
insert(Item.T2, Item.AluminumOre)
insert(Item.T2, Item.IronOre)
insert(Item.T2, Item.CopperOre)
insert(Item.T2, Item.Silicates)
insert(Item.T2, Item.Chondrites)
insert(Item.T3, Item.Biomass)
insert(Item.T4, Item.Hydrogen)
insert(Item.T4, Item.Helium)
insert(Item.T4, Item.Lithium)
insert(Item.T4, Item.Beryllium)
insert(Item.T4, Item.Boron)
insert(Item.T4, Item.Carbon)
insert(Item.T4, Item.Nitrogen)
insert(Item.T4, Item.Oxygen)
insert(Item.T4, Item.Aluminum)
insert(Item.T4, Item.Silicon)
insert(Item.T4, Item.Iron)
insert(Item.T4, Item.Steel)
insert(Item.T4, Item.Silver)
insert(Item.T4, Item.Platinum)
insert(Item.T4, Item.Gold)
insert(Item.T4, Item.Thorium)
insert(Item.T4, Item.Isotopes)
insert(Item.T4, Item.WaterLiquid)
insert(Item.T4, Item.Waste)
insert(Item.T4, Item.AnodeSludge)
insert(Item.T5, Item.Petroleum)
insert(Item.T5, Item.Plastic)
insert(Item.T5, Item.Infolytic)
insert(Item.T5, Item.Glassiron)
insert(Item.T5, Item.TranspAluminum)
insert(Item.T6, Item.EngineShip)
insert(Item.T6, Item.WeaponShip)

-- Production ------------------------------------------------------------------

local Production = require('Systems.Economy.Production')

Production.EnergySolar = Production('Solar Energy Array')
  :addInput(Item.Waste, 1)
  :addOutput(Item.Energy, 5)
  :setDuration(0.5)

Production.EnergyNuclear = Production('Nuclear Reactor')
  :addInput(Item.Isotopes, 1)
  :addOutput(Item.Energy, 10)
  :addOutput(Item.WasteRad, 4)
  :setDuration(0.3)

Production.EnergyFusion = Production('Fusion Reactor')
  :addInput(Item.WaterLiquid, 1000)
  :addOutput(Item.Energy, 240)
  :addOutput(Item.WasteRad, 1)
  :setDuration(0.5)

Production.WaterMelter = Production('Water Melter')
  :addInput(Item.Energy, 2)
  :addInput(Item.WaterIce, 1)
  :addOutput(Item.WaterLiquid, 1)
  :setDuration(0.1)

Production.WaterSplitter = Production('Water Electrolyser')
  :addInput(Item.Energy, 3)
  :addInput(Item.WaterIce, 1)
  :addOutput(Item.Hydrogen, 2)
  :addOutput(Item.Oxygen, 1)
  :setDuration(0.1)

Production.Silicon = Production('Silicon Refinery')
  :addInput(Item.Energy, 3)
  :addInput(Item.Silicates, 12)
  :addOutput(Item.Silicon, 1)
  :addOutput(Item.Waste, 6)
  :setDuration(0.7)

Production.Carbon = Production('Carbon Refinery')
  :addInput(Item.Energy, 3)
  :addInput(Item.Chondrites, 4)
  :addOutput(Item.Carbon, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(0.7)

Production.Aluminum = Production('Aluminum Refinery')
  :addInput(Item.Energy, 6)
  :addInput(Item.AluminumOre, 8)
  :addOutput(Item.Aluminum, 1)
  :addOutput(Item.Waste, 5)
  :setDuration(0.7)

Production.Aluminum = Production('Iron Refinery')
  :addInput(Item.Energy, 5)
  :addInput(Item.IronOre, 7)
  :addOutput(Item.Iron, 1)
  :addOutput(Item.Waste, 4)
  :setDuration(0.6)

Production.Steel = Production('Steel Foundry')
  :addInput(Item.Energy, 5)
  :addInput(Item.Iron, 14)
  :addInput(Item.Carbon, 2)
  :addOutput(Item.Steel, 1)
  :addOutput(Item.Waste, 9)
  :setDuration(0.8)

Production.Copper = Production('Copper Refinery')
  :addInput(Item.Energy, 7)
  :addInput(Item.CopperOre, 11)
  :addOutput(Item.Copper, 2)
  :addOutput(Item.AnodeSludge, 1)
  :addOutput(Item.Waste, 7)
  :setDuration(0.7)

Production.Silver = Production('Silver Recovery Plant')
  :addInput(Item.Energy, 12)
  :addInput(Item.AnodeSludge, 8)
  :addOutput(Item.Silver, 1)
  :addOutput(Item.Waste, 6)
  :setDuration(0.8)

Production.Gold = Production('Gold Recovery Plant')
  :addInput(Item.Energy, 14)
  :addInput(Item.AnodeSludge, 11)
  :addOutput(Item.Gold, 1)
  :addOutput(Item.Waste, 7)
  :setDuration(0.9)

Production.Platinum = Production('Platinum Recovery Plant')
  :addInput(Item.Energy, 20)
  :addInput(Item.AnodeSludge, 16)
  :addOutput(Item.Platinum, 1)
  :addOutput(Item.Waste, 9)
  :setDuration(1.1)

Production.Thorium = Production('Thorium Refinery')
  :addInput(Item.Energy, 13)
  :addInput(Item.ThoriumOre, 12)
  :addOutput(Item.Thorium, 1)
  :addOutput(Item.WasteRad, 2)
  :addOutput(Item.Waste, 5)
  :setDuration(0.9)

Production.Isotopes = Production('Isotope Refinery')
  :addInput(Item.Energy, 5)
  :addInput(Item.Thorium, 20)
  :addOutput(Item.Isotopes, 1)
  :addOutput(Item.WasteRad, 7)
  :addOutput(Item.Waste, 3)
  :setDuration(1.2)

Production.Petroleum = Production('Petroleum Refinery')
  :addInput(Item.Energy, 6)
  :addInput(Item.Biomass, 22)
  :addOutput(Item.Petroleum, 1)
  :addOutput(Item.Waste, 15)
  :setDuration(0.3)

Production.Infolytic = Production('Plastics Factory')
  :addInput(Item.Energy, 11)
  :addInput(Item.Petroleum, 10)
  :addOutput(Item.Plastic, 1)
  :addOutput(Item.Waste, 8)
  :setDuration(0.8)

Production.Infolytic = Production('Infolytic Chip Factory')
  :addInput(Item.Energy, 10)
  :addInput(Item.Plastic, 8)
  :addInput(Item.Gold, 1)
  :addInput(Item.Silicon, 1)
  :addOutput(Item.Infolytic, 1)
  :addOutput(Item.Waste, 2)
  :setDuration(1.4)

Production.TranspAluminum = Production('Transparent Aluminum Factory')
  :addInput(Item.Energy, 5)
  :addInput(Item.Silicon, 5)
  :addInput(Item.Aluminum, 3)
  :addOutput(Item.TranspAlum, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(1.1)

Production.Glassiron = Production('Glassiron Factory')
  :addInput(Item.Energy, 18)
  :addInput(Item.Silicates, 5)
  :addInput(Item.Iron, 3)
  :addInput(Item.Beryllium, 3)
  :addOutput(Item.Glassiron, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(1.4)

Production.HullShip = Production('Ship Hull Drydock')
  :addInput(Item.Energy, 3500)
  :addInput(Item.Glassiron, 20000)
  :addInput(Item.TranspAlum, 1800)
  :addInput(Item.Steel, 3950)
  :addInput(Item.Gold, 570)
  :addInput(Item.Platinum, 190)
  :addInput(Item.Infolytic, 325)
  :addOutput(Item.HullShip, 1)
  :addOutput(Item.Waste, 725)
  :setDuration(220.0)


--------------------------------------------------------------------------------
