-- This is a placeholder file for directly adding game content that would
-- typically be added in mod format

-- Items -----------------------------------------------------------------------

local Production = require('Systems.Economy.Production')
local Item = require('Systems.Economy.Item')

Item.T0 = {} -- nonsolid, energy
Item.T1 = {} -- nonsolid, information
Item.T2 = {} -- solid, raw, inanimate
Item.T3 = {} -- solid, raw, animate
Item.T4 = {} -- solid, processed, elemental
Item.T5 = {} -- solid, processed, constructed
Item.T6 = {} -- solid, processed, constructed, ship component
Item.T7 = {} -- solid, processed, constructed, ship
Item.T8 = {} -- solid, processed, constructed, station

Production.P0 = {} -- Powerplant
Production.P1 = {} -- Refinery
Production.P2 = {} -- Factory
Production.P3 = {} -- Drydock

--                       NAME                 UNIT MASS   ENERGY-DENSITY
Item.Energy      = Item("Energy Cell",                1,   1.00)
Item.Data        = Item("Data Cube",                  1,   2.10)
Item.Information = Item("Info Wafer",                 1,   3.82)
Item.Biomass     = Item("Biomass",                    8,   5.00)
Item.WaterLiquid = Item("Liquid Water",              10,   0.80)
Item.WaterIce    = Item("Water Ice",                  8,   0.50)
Item.Silicates   = Item("Silicate Ore",               4,   0.30)
Item.Chondrites  = Item("Carboniferous Ore",          7,   1.40)
Item.AluminumOre = Item("Aluminum Ore",               7,   0.60)
Item.IronOre     = Item("Iron Ore",                  10,   0.68)
Item.CopperOre   = Item("Copper Ore",                11,   0.74)
Item.ThoriumOre  = Item("Thorium Ore",               19,   3.50)
Item.Hydrogen    = Item("Hydrogen",                   1,   2.00)
Item.Helium      = Item("Helium",                     1,   0.01)
Item.Lithium     = Item("Lithium",                    1,   0.20)
Item.Beryllium   = Item("Beryllium",                  2,   0.30)
Item.Boron       = Item("Boron",                      2,   0.20)
Item.Carbon      = Item("Carbon",                     2,   0.30)
Item.Nitrogen    = Item("Nitrogen",                   1,   0.05)
Item.Oxygen      = Item("Oxygen",                     1,   2.00)
Item.Aluminum    = Item("Aluminum",                   3,   0.80)
Item.Silicon     = Item("Silicon",                    2,   0.60)
Item.Iron        = Item("Iron",                       5,   1.00)
Item.Copper      = Item("Copper",                     5,   1.00)
Item.Silver      = Item("Silver",                     5,   1.50)
Item.Gold        = Item("Gold",                       6,   2.00)
Item.Platinum    = Item("Platinum",                   8,   3.00)
Item.Thorium     = Item("Thorium",                    9,  27.00)
Item.Steel       = Item("Steel",                      7,   1.00)
Item.Petroleum   = Item("Petroleum",                  6,   3.50)
Item.Plastic     = Item("Plastic",                    4,   1.90)
Item.Infolytic   = Item("Infolytic Chip",             5,   1.35)
Item.Glassiron   = Item("Glassiron",                 12,   1.00)
Item.TranspAlum  = Item("Transparent Aluminum",       7,   1.70)
Item.Isotopes    = Item("Radioactive Isotopes",      24,  50.00)
Item.WasteRad    = Item("Radioactive Waste",         15,   2.50)
Item.Waste       = Item("Waste",                      2,   0.50)
Item.AnodeSludge = Item("Anode Sludge",              10,   0.90)
Item.HullShip    = Item("Ship Hull",              15000,  50.00)
Item.EngineShip  = Item("Ship Engine",              500,  20.00)
Item.WeaponShip  = Item("Ship Weapon",              100,  10.00)
Item.Station     = Item("Space Station",        1550000,  40.00)

insert(Item.T0, Item.Energy)
insert(Item.T1, Item.Data)
insert(Item.T1, Item.Information)
insert(Item.T2, Item.WaterIce)
insert(Item.T2, Item.AluminumOre)
insert(Item.T2, Item.IronOre)
insert(Item.T2, Item.CopperOre)
insert(Item.T2, Item.ThoriumOre)
insert(Item.T2, Item.Silicates)
insert(Item.T2, Item.Chondrites)
insert(Item.T3, Item.Biomass)
insert(Item.T4, Item.Hydrogen)
insert(Item.T4, Item.Helium)
insert(Item.T4, Item.Lithium)
insert(Item.T4, Item.Beryllium)
insert(Item.T4, Item.Boron)
insert(Item.T4, Item.Carbon)
insert(Item.T4, Item.Nitrogen)
insert(Item.T4, Item.Oxygen)
insert(Item.T4, Item.Aluminum)
insert(Item.T4, Item.Silicon)
insert(Item.T4, Item.Iron)
insert(Item.T4, Item.Steel)
insert(Item.T4, Item.Silver)
insert(Item.T4, Item.Platinum)
insert(Item.T4, Item.Gold)
insert(Item.T4, Item.Thorium)
insert(Item.T4, Item.Isotopes)
insert(Item.T4, Item.WaterLiquid)
insert(Item.T4, Item.Waste)
insert(Item.T4, Item.AnodeSludge)
insert(Item.T5, Item.Petroleum)
insert(Item.T5, Item.Plastic)
insert(Item.T5, Item.Infolytic)
insert(Item.T5, Item.Glassiron)
insert(Item.T5, Item.TranspAluminum)
insert(Item.T6, Item.EngineShip)
insert(Item.T6, Item.WeaponShip)
insert(Item.T7, Item.HullShip)
insert(Item.T8, Item.Station)

-- Production ------------------------------------------------------------------

local Production = require('Systems.Economy.Production')

Production.EnergySolar = Production('Solar Energy Array')
  :addOutput(Item.Energy, 5)
  :setDuration(10.0)
insert(Production.P0, Production.EnergySolar)

Production.EnergyNuclear = Production('Nuclear Reactor')
  :addInput(Item.Isotopes, 1)
  :addOutput(Item.Energy, 10)
  :addOutput(Item.WasteRad, 4)
  :setDuration(12.0)
insert(Production.P0, Production.EnergyNuclear)

Production.EnergyFusion = Production('Fusion Reactor')
  :addInput(Item.WaterLiquid, 1000)
  :addOutput(Item.Energy, 240)
  :addOutput(Item.WasteRad, 1)
  :setDuration(20.0)
insert(Production.P0, Production.EnergyFusion)

Production.WaterMelter = Production('Water Melter')
  :addInput(Item.Energy, 2)
  :addInput(Item.WaterIce, 1)
  :addOutput(Item.WaterLiquid, 1)
  :setDuration(6.0)
insert(Production.P1, Production.WaterMelter)

Production.Silicon = Production('Silicon Refinery')
  :addInput(Item.Energy, 3)
  :addInput(Item.Silicates, 12)
  :addOutput(Item.Silicon, 1)
  :addOutput(Item.Waste, 6)
  :setDuration(12.0)
insert(Production.P1, Production.Silicon)

Production.Carbon = Production('Carbon Refinery')
  :addInput(Item.Energy, 3)
  :addInput(Item.Chondrites, 4)
  :addOutput(Item.Carbon, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(13.0)
insert(Production.P1, Production.Carbon)

Production.Aluminum = Production('Aluminum Refinery')
  :addInput(Item.Energy, 6)
  :addInput(Item.AluminumOre, 8)
  :addOutput(Item.Aluminum, 1)
  :addOutput(Item.Waste, 5)
  :setDuration(15.0)
insert(Production.P1, Production.Aluminum)

Production.Iron = Production('Iron Refinery')
  :addInput(Item.Energy, 5)
  :addInput(Item.IronOre, 7)
  :addOutput(Item.Iron, 1)
  :addOutput(Item.Waste, 4)
  :setDuration(14.0)
insert(Production.P1, Production.Iron)

Production.Copper = Production('Copper Refinery')
  :addInput(Item.Energy, 7)
  :addInput(Item.CopperOre, 11)
  :addOutput(Item.Copper, 2)
  :addOutput(Item.AnodeSludge, 1)
  :addOutput(Item.Waste, 7)
  :setDuration(16.0)
insert(Production.P1, Production.Copper)

Production.Thorium = Production('Thorium Refinery')
  :addInput(Item.Energy, 13)
  :addInput(Item.ThoriumOre, 12)
  :addOutput(Item.Thorium, 1)
  :addOutput(Item.WasteRad, 2)
  :addOutput(Item.Waste, 5)
  :setDuration(20.0)
insert(Production.P1, Production.Thorium)

Production.Petroleum = Production('Petroleum Refinery')
  :addInput(Item.Energy, 6)
  :addInput(Item.Biomass, 22)
  :addOutput(Item.Petroleum, 1)
  :addOutput(Item.Waste, 15)
  :setDuration(14.0)
insert(Production.P1, Production.Petroleum)

Production.WaterSplitter = Production('Water Electrolyser')
  :addInput(Item.Energy, 3)
  :addInput(Item.WaterLiquid, 1)
  :addOutput(Item.Hydrogen, 2)
  :addOutput(Item.Oxygen, 1)
  :setDuration(5.0)
insert(Production.P2, Production.WaterSplitter)

Production.Steel = Production('Steel Foundry')
  :addInput(Item.Energy, 5)
  :addInput(Item.Iron, 14)
  :addInput(Item.Carbon, 2)
  :addOutput(Item.Steel, 1)
  :addOutput(Item.Waste, 9)
  :setDuration(16.0)
insert(Production.P2, Production.Steel)

Production.Silver = Production('Silver Recovery Plant')
  :addInput(Item.Energy, 12)
  :addInput(Item.AnodeSludge, 8)
  :addOutput(Item.Silver, 1)
  :addOutput(Item.Waste, 6)
  :setDuration(18.0)
insert(Production.P2, Production.Silver)

Production.Gold = Production('Gold Recovery Plant')
  :addInput(Item.Energy, 14)
  :addInput(Item.AnodeSludge, 11)
  :addOutput(Item.Gold, 1)
  :addOutput(Item.Waste, 7)
  :setDuration(21.0)
insert(Production.P2, Production.Gold)

Production.Platinum = Production('Platinum Recovery Plant')
  :addInput(Item.Energy, 20)
  :addInput(Item.AnodeSludge, 16)
  :addOutput(Item.Platinum, 1)
  :addOutput(Item.Waste, 9)
  :setDuration(25.0)
insert(Production.P2, Production.Platinum)

Production.Isotopes = Production('Isotope Factory')
  :addInput(Item.Energy, 5)
  :addInput(Item.Thorium, 20)
  :addOutput(Item.Isotopes, 1)
  :addOutput(Item.WasteRad, 7)
  :addOutput(Item.Waste, 3)
  :setDuration(11.0)
insert(Production.P2, Production.Isotopes)

Production.Plastic = Production('Plastics Factory')
  :addInput(Item.Energy, 11)
  :addInput(Item.Petroleum, 10)
  :addOutput(Item.Plastic, 1)
  :addOutput(Item.Waste, 8)
  :setDuration(9.0)
insert(Production.P2, Production.Plastic)

Production.Infolytic = Production('Infolytic Chip Factory')
  :addInput(Item.Energy, 10)
  :addInput(Item.Plastic, 8)
  :addInput(Item.Gold, 1)
  :addInput(Item.Silicon, 1)
  :addOutput(Item.Infolytic, 1)
  :addOutput(Item.Waste, 2)
  :setDuration(11)
insert(Production.P2, Production.Infolytic)

Production.TranspAluminum = Production('Transparent Aluminum Factory')
  :addInput(Item.Energy, 5)
  :addInput(Item.Silicon, 5)
  :addInput(Item.Aluminum, 3)
  :addOutput(Item.TranspAlum, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(13.0)
insert(Production.P2, Production.TranspAluminum)

Production.Glassiron = Production('Glassiron Factory')
  :addInput(Item.Energy, 18)
  :addInput(Item.Silicon, 5)
  :addInput(Item.Iron, 3)
  :addInput(Item.Beryllium, 3)
  :addOutput(Item.Glassiron, 1)
  :addOutput(Item.Waste, 3)
  :setDuration(17.0)
insert(Production.P2, Production.Glassiron)

Production.HullShip = Production('Ship Hull Drydock')
  :addInput(Item.Energy, 1500)
  :addInput(Item.Glassiron, 10000)
  :addInput(Item.TranspAlum, 900)
  :addInput(Item.Steel, 1850)
  :addInput(Item.Gold, 285)
  :addInput(Item.Platinum, 95)
  :addInput(Item.Infolytic, 165)
  :addInput(Item.Thorium, 35)
  :addOutput(Item.HullShip, 1)
  :addOutput(Item.Waste, 725)
  :setDuration(1800.0)
insert(Production.P3, Production.HullShip)

Production.Station = Production('Space Station Fabricator')
  :addInput(Item.Energy, 350000)
  :addInput(Item.Glassiron, 1000000)
  :addInput(Item.TranspAlum, 180000)
  :addInput(Item.Steel, 395000)
  :addInput(Item.Gold, 57000)
  :addInput(Item.Platinum, 19000)
  :addInput(Item.Infolytic, 32500)
  :addInput(Item.Thorium, 640)
  :addOutput(Item.HullShip, 1)
  :addOutput(Item.Waste, 9750)
  :setDuration(14400.0)
insert(Production.P3, Production.Station)

--------------------------------------------------------------------------------
