---@meta

---@class Button
---@field KeyboardBackquote integer 
---@field KeyboardBackslash integer 
---@field KeyboardBracketLeft integer 
---@field KeyboardBracketRight integer 
---@field KeyboardComma integer 
---@field KeyboardKey0 integer 
---@field KeyboardKey1 integer 
---@field KeyboardKey2 integer 
---@field KeyboardKey3 integer 
---@field KeyboardKey4 integer 
---@field KeyboardKey5 integer 
---@field KeyboardKey6 integer 
---@field KeyboardKey7 integer 
---@field KeyboardKey8 integer 
---@field KeyboardKey9 integer 
---@field KeyboardEqual integer 
---@field KeyboardIntlBackslash integer 
---@field KeyboardIntlRo integer 
---@field KeyboardIntlYen integer 
---@field KeyboardA integer 
---@field KeyboardB integer 
---@field KeyboardC integer 
---@field KeyboardD integer 
---@field KeyboardE integer 
---@field KeyboardF integer 
---@field KeyboardG integer 
---@field KeyboardH integer 
---@field KeyboardI integer 
---@field KeyboardJ integer 
---@field KeyboardK integer 
---@field KeyboardL integer 
---@field KeyboardM integer 
---@field KeyboardN integer 
---@field KeyboardO integer 
---@field KeyboardP integer 
---@field KeyboardQ integer 
---@field KeyboardR integer 
---@field KeyboardS integer 
---@field KeyboardT integer 
---@field KeyboardU integer 
---@field KeyboardV integer 
---@field KeyboardW integer 
---@field KeyboardX integer 
---@field KeyboardY integer 
---@field KeyboardZ integer 
---@field KeyboardMinus integer 
---@field KeyboardPeriod integer 
---@field KeyboardQuote integer 
---@field KeyboardSemicolon integer 
---@field KeyboardSlash integer 
---@field KeyboardAltLeft integer 
---@field KeyboardAltRight integer 
---@field KeyboardBackspace integer 
---@field KeyboardCapsLock integer 
---@field KeyboardContextMenu integer 
---@field KeyboardControlLeft integer 
---@field KeyboardControlRight integer 
---@field KeyboardEnter integer 
---@field KeyboardSuperLeft integer 
---@field KeyboardSuperRight integer 
---@field KeyboardShiftLeft integer 
---@field KeyboardShiftRight integer 
---@field KeyboardSpace integer 
---@field KeyboardTab integer 
---@field KeyboardConvert integer 
---@field KeyboardKanaMode integer 
---@field KeyboardLang1 integer 
---@field KeyboardLang2 integer 
---@field KeyboardLang3 integer 
---@field KeyboardLang4 integer 
---@field KeyboardLang5 integer 
---@field KeyboardNonConvert integer 
---@field KeyboardDelete integer 
---@field KeyboardEnd integer 
---@field KeyboardHelp integer 
---@field KeyboardHome integer 
---@field KeyboardInsert integer 
---@field KeyboardPageDown integer 
---@field KeyboardPageUp integer 
---@field KeyboardDown integer 
---@field KeyboardLeft integer 
---@field KeyboardRight integer 
---@field KeyboardUp integer 
---@field KeyboardNumLock integer 
---@field KeyboardNumpad0 integer 
---@field KeyboardNumpad1 integer 
---@field KeyboardNumpad2 integer 
---@field KeyboardNumpad3 integer 
---@field KeyboardNumpad4 integer 
---@field KeyboardNumpad5 integer 
---@field KeyboardNumpad6 integer 
---@field KeyboardNumpad7 integer 
---@field KeyboardNumpad8 integer 
---@field KeyboardNumpad9 integer 
---@field KeyboardNumpadAdd integer 
---@field KeyboardNumpadBackspace integer 
---@field KeyboardNumpadClear integer 
---@field KeyboardNumpadClearEntry integer 
---@field KeyboardNumpadComma integer 
---@field KeyboardNumpadDecimal integer 
---@field KeyboardNumpadDivide integer 
---@field KeyboardNumpadEnter integer 
---@field KeyboardNumpadEqual integer 
---@field KeyboardNumpadHash integer 
---@field KeyboardNumpadMemoryAdd integer 
---@field KeyboardNumpadMemoryClear integer 
---@field KeyboardNumpadMemoryRecall integer 
---@field KeyboardNumpadMemoryStore integer 
---@field KeyboardNumpadMemorySubtract integer 
---@field KeyboardNumpadMultiply integer 
---@field KeyboardNumpadParenLeft integer 
---@field KeyboardNumpadParenRight integer 
---@field KeyboardNumpadStar integer 
---@field KeyboardNumpadSubtract integer 
---@field KeyboardEscape integer 
---@field KeyboardFn integer 
---@field KeyboardFnLock integer 
---@field KeyboardPrintScreen integer 
---@field KeyboardScrollLock integer 
---@field KeyboardPause integer 
---@field KeyboardBrowserBack integer 
---@field KeyboardBrowserFavorites integer 
---@field KeyboardBrowserForward integer 
---@field KeyboardBrowserHome integer 
---@field KeyboardBrowserRefresh integer 
---@field KeyboardBrowserSearch integer 
---@field KeyboardBrowserStop integer 
---@field KeyboardEject integer 
---@field KeyboardLaunchApp1 integer 
---@field KeyboardLaunchApp2 integer 
---@field KeyboardLaunchMail integer 
---@field KeyboardMediaPlayPause integer 
---@field KeyboardMediaSelect integer 
---@field KeyboardMediaStop integer 
---@field KeyboardMediaTrackNext integer 
---@field KeyboardMediaTrackPrevious integer 
---@field KeyboardPower integer 
---@field KeyboardSleep integer 
---@field KeyboardAudioVolumeDown integer 
---@field KeyboardAudioVolumeMute integer 
---@field KeyboardAudioVolumeUp integer 
---@field KeyboardWakeUp integer 
---@field KeyboardMeta integer 
---@field KeyboardHyper integer 
---@field KeyboardTurbo integer 
---@field KeyboardAbort integer 
---@field KeyboardResume integer 
---@field KeyboardSuspend integer 
---@field KeyboardAgain integer 
---@field KeyboardCopy integer 
---@field KeyboardCut integer 
---@field KeyboardFind integer 
---@field KeyboardOpen integer 
---@field KeyboardPaste integer 
---@field KeyboardProps integer 
---@field KeyboardSelect integer 
---@field KeyboardUndo integer 
---@field KeyboardHiragana integer 
---@field KeyboardKatakana integer 
---@field KeyboardF1 integer 
---@field KeyboardF2 integer 
---@field KeyboardF3 integer 
---@field KeyboardF4 integer 
---@field KeyboardF5 integer 
---@field KeyboardF6 integer 
---@field KeyboardF7 integer 
---@field KeyboardF8 integer 
---@field KeyboardF9 integer 
---@field KeyboardF10 integer 
---@field KeyboardF11 integer 
---@field KeyboardF12 integer 
---@field KeyboardF13 integer 
---@field KeyboardF14 integer 
---@field KeyboardF15 integer 
---@field KeyboardF16 integer 
---@field KeyboardF17 integer 
---@field KeyboardF18 integer 
---@field KeyboardF19 integer 
---@field KeyboardF20 integer 
---@field KeyboardF21 integer 
---@field KeyboardF22 integer 
---@field KeyboardF23 integer 
---@field KeyboardF24 integer 
---@field KeyboardF25 integer 
---@field KeyboardF26 integer 
---@field KeyboardF27 integer 
---@field KeyboardF28 integer 
---@field KeyboardF29 integer 
---@field KeyboardF30 integer 
---@field KeyboardF31 integer 
---@field KeyboardF32 integer 
---@field KeyboardF33 integer 
---@field KeyboardF34 integer 
---@field KeyboardF35 integer 
---@field MouseLeft integer 
---@field MouseMiddle integer 
---@field MouseRight integer 
---@field MouseForward integer 
---@field MouseBack integer 
---@field MouseX1 integer 
---@field MouseX2 integer 
---@field MouseDeltaX integer 
---@field MouseDeltaY integer 
---@field MouseScrollX integer 
---@field MouseScrollY integer 
---@field MouseScrollPixelX integer 
---@field MouseScrollPixelY integer 
---@field GamepadSouth integer 
---@field GamepadEast integer 
---@field GamepadNorth integer 
---@field GamepadWest integer 
---@field GamepadC integer 
---@field GamepadZ integer 
---@field GamepadLeftTrigger integer 
---@field GamepadLeftTrigger2 integer 
---@field GamepadRightTrigger integer 
---@field GamepadRightTrigger2 integer 
---@field GamepadSelect integer 
---@field GamepadStart integer 
---@field GamepadMode integer 
---@field GamepadLeftThumb integer 
---@field GamepadRightThumb integer 
---@field GamepadDPadUp integer 
---@field GamepadDPadDown integer 
---@field GamepadDPadLeft integer 
---@field GamepadDPadRight integer 
---@field GamepadLeftStickX integer 
---@field GamepadLeftStickY integer 
---@field GamepadLeftZ integer 
---@field GamepadRightStickX integer 
---@field GamepadRightStickY integer 
---@field GamepadRightZ integer 
---@field TouchpadX integer 
---@field TouchpadY integer 
---@field TouchpadMagnifyDelta integer 
---@field TouchpadRotateDelta integer 
---@field SystemExit integer 
Button = {
    KeyboardBackquote = 0,
    KeyboardBackslash = 1,
    KeyboardBracketLeft = 2,
    KeyboardBracketRight = 3,
    KeyboardComma = 4,
    KeyboardKey0 = 5,
    KeyboardKey1 = 6,
    KeyboardKey2 = 7,
    KeyboardKey3 = 8,
    KeyboardKey4 = 9,
    KeyboardKey5 = 10,
    KeyboardKey6 = 11,
    KeyboardKey7 = 12,
    KeyboardKey8 = 13,
    KeyboardKey9 = 14,
    KeyboardEqual = 15,
    KeyboardIntlBackslash = 16,
    KeyboardIntlRo = 17,
    KeyboardIntlYen = 18,
    KeyboardA = 19,
    KeyboardB = 20,
    KeyboardC = 21,
    KeyboardD = 22,
    KeyboardE = 23,
    KeyboardF = 24,
    KeyboardG = 25,
    KeyboardH = 26,
    KeyboardI = 27,
    KeyboardJ = 28,
    KeyboardK = 29,
    KeyboardL = 30,
    KeyboardM = 31,
    KeyboardN = 32,
    KeyboardO = 33,
    KeyboardP = 34,
    KeyboardQ = 35,
    KeyboardR = 36,
    KeyboardS = 37,
    KeyboardT = 38,
    KeyboardU = 39,
    KeyboardV = 40,
    KeyboardW = 41,
    KeyboardX = 42,
    KeyboardY = 43,
    KeyboardZ = 44,
    KeyboardMinus = 45,
    KeyboardPeriod = 46,
    KeyboardQuote = 47,
    KeyboardSemicolon = 48,
    KeyboardSlash = 49,
    KeyboardAltLeft = 50,
    KeyboardAltRight = 51,
    KeyboardBackspace = 52,
    KeyboardCapsLock = 53,
    KeyboardContextMenu = 54,
    KeyboardControlLeft = 55,
    KeyboardControlRight = 56,
    KeyboardEnter = 57,
    KeyboardSuperLeft = 58,
    KeyboardSuperRight = 59,
    KeyboardShiftLeft = 60,
    KeyboardShiftRight = 61,
    KeyboardSpace = 62,
    KeyboardTab = 63,
    KeyboardConvert = 64,
    KeyboardKanaMode = 65,
    KeyboardLang1 = 66,
    KeyboardLang2 = 67,
    KeyboardLang3 = 68,
    KeyboardLang4 = 69,
    KeyboardLang5 = 70,
    KeyboardNonConvert = 71,
    KeyboardDelete = 72,
    KeyboardEnd = 73,
    KeyboardHelp = 74,
    KeyboardHome = 75,
    KeyboardInsert = 76,
    KeyboardPageDown = 77,
    KeyboardPageUp = 78,
    KeyboardDown = 79,
    KeyboardLeft = 80,
    KeyboardRight = 81,
    KeyboardUp = 82,
    KeyboardNumLock = 83,
    KeyboardNumpad0 = 84,
    KeyboardNumpad1 = 85,
    KeyboardNumpad2 = 86,
    KeyboardNumpad3 = 87,
    KeyboardNumpad4 = 88,
    KeyboardNumpad5 = 89,
    KeyboardNumpad6 = 90,
    KeyboardNumpad7 = 91,
    KeyboardNumpad8 = 92,
    KeyboardNumpad9 = 93,
    KeyboardNumpadAdd = 94,
    KeyboardNumpadBackspace = 95,
    KeyboardNumpadClear = 96,
    KeyboardNumpadClearEntry = 97,
    KeyboardNumpadComma = 98,
    KeyboardNumpadDecimal = 99,
    KeyboardNumpadDivide = 100,
    KeyboardNumpadEnter = 101,
    KeyboardNumpadEqual = 102,
    KeyboardNumpadHash = 103,
    KeyboardNumpadMemoryAdd = 104,
    KeyboardNumpadMemoryClear = 105,
    KeyboardNumpadMemoryRecall = 106,
    KeyboardNumpadMemoryStore = 107,
    KeyboardNumpadMemorySubtract = 108,
    KeyboardNumpadMultiply = 109,
    KeyboardNumpadParenLeft = 110,
    KeyboardNumpadParenRight = 111,
    KeyboardNumpadStar = 112,
    KeyboardNumpadSubtract = 113,
    KeyboardEscape = 114,
    KeyboardFn = 115,
    KeyboardFnLock = 116,
    KeyboardPrintScreen = 117,
    KeyboardScrollLock = 118,
    KeyboardPause = 119,
    KeyboardBrowserBack = 120,
    KeyboardBrowserFavorites = 121,
    KeyboardBrowserForward = 122,
    KeyboardBrowserHome = 123,
    KeyboardBrowserRefresh = 124,
    KeyboardBrowserSearch = 125,
    KeyboardBrowserStop = 126,
    KeyboardEject = 127,
    KeyboardLaunchApp1 = 128,
    KeyboardLaunchApp2 = 129,
    KeyboardLaunchMail = 130,
    KeyboardMediaPlayPause = 131,
    KeyboardMediaSelect = 132,
    KeyboardMediaStop = 133,
    KeyboardMediaTrackNext = 134,
    KeyboardMediaTrackPrevious = 135,
    KeyboardPower = 136,
    KeyboardSleep = 137,
    KeyboardAudioVolumeDown = 138,
    KeyboardAudioVolumeMute = 139,
    KeyboardAudioVolumeUp = 140,
    KeyboardWakeUp = 141,
    KeyboardMeta = 142,
    KeyboardHyper = 143,
    KeyboardTurbo = 144,
    KeyboardAbort = 145,
    KeyboardResume = 146,
    KeyboardSuspend = 147,
    KeyboardAgain = 148,
    KeyboardCopy = 149,
    KeyboardCut = 150,
    KeyboardFind = 151,
    KeyboardOpen = 152,
    KeyboardPaste = 153,
    KeyboardProps = 154,
    KeyboardSelect = 155,
    KeyboardUndo = 156,
    KeyboardHiragana = 157,
    KeyboardKatakana = 158,
    KeyboardF1 = 159,
    KeyboardF2 = 160,
    KeyboardF3 = 161,
    KeyboardF4 = 162,
    KeyboardF5 = 163,
    KeyboardF6 = 164,
    KeyboardF7 = 165,
    KeyboardF8 = 166,
    KeyboardF9 = 167,
    KeyboardF10 = 168,
    KeyboardF11 = 169,
    KeyboardF12 = 170,
    KeyboardF13 = 171,
    KeyboardF14 = 172,
    KeyboardF15 = 173,
    KeyboardF16 = 174,
    KeyboardF17 = 175,
    KeyboardF18 = 176,
    KeyboardF19 = 177,
    KeyboardF20 = 178,
    KeyboardF21 = 179,
    KeyboardF22 = 180,
    KeyboardF23 = 181,
    KeyboardF24 = 182,
    KeyboardF25 = 183,
    KeyboardF26 = 184,
    KeyboardF27 = 185,
    KeyboardF28 = 186,
    KeyboardF29 = 187,
    KeyboardF30 = 188,
    KeyboardF31 = 189,
    KeyboardF32 = 190,
    KeyboardF33 = 191,
    KeyboardF34 = 192,
    KeyboardF35 = 193,
    MouseLeft = 194,
    MouseMiddle = 195,
    MouseRight = 196,
    MouseForward = 197,
    MouseBack = 198,
    MouseX1 = 199,
    MouseX2 = 200,
    MouseDeltaX = 201,
    MouseDeltaY = 202,
    MouseScrollX = 203,
    MouseScrollY = 204,
    MouseScrollPixelX = 205,
    MouseScrollPixelY = 206,
    GamepadSouth = 207,
    GamepadEast = 208,
    GamepadNorth = 209,
    GamepadWest = 210,
    GamepadC = 211,
    GamepadZ = 212,
    GamepadLeftTrigger = 213,
    GamepadLeftTrigger2 = 214,
    GamepadRightTrigger = 215,
    GamepadRightTrigger2 = 216,
    GamepadSelect = 217,
    GamepadStart = 218,
    GamepadMode = 219,
    GamepadLeftThumb = 220,
    GamepadRightThumb = 221,
    GamepadDPadUp = 222,
    GamepadDPadDown = 223,
    GamepadDPadLeft = 224,
    GamepadDPadRight = 225,
    GamepadLeftStickX = 226,
    GamepadLeftStickY = 227,
    GamepadLeftZ = 228,
    GamepadRightStickX = 229,
    GamepadRightStickY = 230,
    GamepadRightZ = 231,
    TouchpadX = 232,
    TouchpadY = 233,
    TouchpadMagnifyDelta = 234,
    TouchpadRotateDelta = 235,
    SystemExit = 236,
}

