---@enum Weapon
Enums.Weapon = {
    Category = {
        Turret = 1,
        Bay = 2,
    },
    Type = {
        Laser = 1,
        Plasma = 2,
        LaserGreen = 3,
        LaserBlue = 4,
        LaserViolet = 5,
        LaserBolt = 6,
        XLLongChargeLaser = 7,
        MissileRocket = 8,
        MissileTorpedo = 9,
        FlakCannon = 10,
        Railgun = 11,
    },
    LaserFamily = {
        Red = 1,
        Green = 2,
        Blue = 3,
        Violet = 4,
    },
    LaserProfile = {
        Red = 1,
        Green = 2,
        Blue = 3,
        Violet = 4,
    },
    Projectile = {
        Plasma = 1,
        LaserBolt = 2,
        Flak = 3,
        RailSlug = 4,
    },
    Beam = {
        Laser = 1,
    },
    Effect = {
        Beam = 1,
        Projectile = 2,
    },
    Visual = {
        Beam = 1,
        Pulse = 2,
    },
    FireMode = {
        Volley = 1,
        Sequence = 2,
    },
    CapacityPolicy = {
        Burst = 1,
        Sustain = 2,
    },
    MountSizeClass = {
        SM = "sm",
        M = "m",
        L = "l",
        XL = "xl",
    },
    CapacitorGroup = {
        Laser = 1,
        Plasma = 2,
    },
    Family = {
        Laser = "laser",
        Plasma = "plasma",
        Missile = "missile",
    },
    Variant = {
        ShortBurst = "short-burst",
        FastBolt = "fast-bolt",
        FastSmall = "fast-small",
        Guided = "guided",
        Rocket = "rocket",
        Torpedo = "torpedo",
        LongCharge = "long-charge",
    },
    ProceduralKey = {
        BurstLaser = "burstLaser",
        BurstLaserGreen = "burstLaserGreen",
        BurstLaserBlue = "burstLaserBlue",
        BurstLaserViolet = "burstLaserViolet",
        FastPlasma = "fastPlasma",
        Missile = "missile",
        RocketM = "rocketM",
        TorpedoL = "torpedoL",
        LongChargeXL = "longChargeXL",
        FastBolt = "fastBolt",
        Flak = "flakCannon",
        Railgun = "assaultRailgun",
    },
    LauncherFamily = {
        Missile = "missile-launcher",
    },
    IdentityKind = {
        Builtin = "builtin",
        Procedural = "procedural",
        ProceduralWeapon = "procedural-weapon",
    },
    CombatRole = {
        Line = "line",
        Heavy = "heavy",
        PointDefense = "point-defense",
        Missile = "missile",
        CapitalHeavy = "capital-heavy",
    },
    MountRole = {
        Line = "line",
        Heavy = "heavy",
        PointDefense = "point-defense",
        Missile = "missile",
        CapitalHeavy = "capital-heavy",
    },
    MountId = {
        ForeOuterPort = "fore_outer_port",
        ForeOuterStarboard = "fore_outer_starboard",
        ForeInnerPort = "fore_inner_port",
        ForeInnerStarboard = "fore_inner_starboard",
        ForePdOuterPort = "fore_pd_outer_port",
        ForePdOuterStarboard = "fore_pd_outer_starboard",
        MidPdPort = "mid_pd_port",
        MidPdStarboard = "mid_pd_starboard",
        MidPort = "mid_port",
        MidStarboard = "mid_starboard",
        MidOuterPort = "mid_outer_port",
        MidOuterStarboard = "mid_outer_starboard",
        ForeHeavyPort = "fore_heavy_port",
        ForeHeavyStarboard = "fore_heavy_starboard",
        MidHeavyPort = "mid_heavy_port",
        MidHeavyStarboard = "mid_heavy_starboard",
        FlakBatteryPort = "flak_battery_port",
        FlakBatteryStarboard = "flak_battery_starboard",
        RailgunBatteryPort = "railgun_battery_port",
        RailgunBatteryStarboard = "railgun_battery_starboard",
        ForePdBottomPort = "fore_pd_bottom_port",
        ForePdBottomStarboard = "fore_pd_bottom_starboard",
        MidPdBottomPort = "mid_pd_bottom_port",
        MidPdBottomStarboard = "mid_pd_bottom_starboard",
        AftPdBottomPort = "aft_pd_bottom_port",
        AftPdBottomStarboard = "aft_pd_bottom_starboard",
        AftInnerPort = "aft_inner_port",
        AftInnerStarboard = "aft_inner_starboard",
        AftPdPort = "aft_pd_port",
        AftPdStarboard = "aft_pd_starboard",
        AftOuterPort = "aft_outer_port",
        AftOuterStarboard = "aft_outer_starboard",
    },
    MountPairId = {
        ForeOuter = "fore_outer",
        ForeInner = "fore_inner",
        ForePdOuter = "fore_pd_outer",
        MidPd = "mid_pd",
        Mid = "mid",
        MidOuter = "mid_outer",
        ForeHeavy = "fore_heavy",
        MidHeavy = "mid_heavy",
        FlakBattery = "flak_battery",
        RailgunBattery = "railgun_battery",
        ForePdBottom = "fore_pd_bottom",
        MidPdBottom = "mid_pd_bottom",
        AftInner = "aft_inner",
        AftPd = "aft_pd",
        AftPdBottom = "aft_pd_bottom",
        AftOuter = "aft_outer",
    },
    MountZone = {
        Fore = "fore",
        Mid = "mid",
        Aft = "aft",
    },
    MountSide = {
        Port = "port",
        Starboard = "starboard",
    },
    MountSurfaceBand = {
        Top = "top",
        Bottom = "bottom",
        Dorsal = "dorsal",
        Ventral = "ventral",
        Underside = "underside",
        Side = "side",
    },
}
