name: Build Binaries

on:
  pull_request:
  push:
    branches:
      - main

env:
  BUILD_TYPE: RelWithDebInfo

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Create Build Environment
        run: cmake -B build
      - name: Build
        run: cmake --build ./build --config RelWithDebInfo --parallel
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-win32
          path: ${{github.workspace}}/bin/*
      - name: Upload binary with assets
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-distro-win32
          path: |
            ${{github.workspace}}/bin/*
            !${{github.workspace}}/bin/*.pdb
            ${{github.workspace}}/docs/*
            ${{github.workspace}}/libphx/script/*
            ${{github.workspace}}/res/*
            ${{github.workspace}}/script/*
            ${{github.workspace}}/LICENSE
            ${{github.workspace}}/README.md

  build-macos:
    name: Build macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Create Build Environment
        run: cmake -B build
      - name: Build
        run: cmake --build ./build --config RelWithDebInfo --parallel
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-macos
          path: ${{github.workspace}}/bin/*

  build-ubuntu:
    name: Build Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update packages
        run: sudo apt-get update
      - name: Install packages
        run: sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libasound2-dev
      - name: Create Build Environment
        run: cmake -B build
      - name: Build
        run: cmake --build ./build --config RelWithDebInfo --parallel
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-ubuntu2004
          path: ${{github.workspace}}/bin/*

  release:
    name: Update 'latest' release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - build-windows
      - build-macos
      - build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Zip artifacts
        run: for dir in $(ls); do cd $dir && zip ../$dir.zip ./* -r && cd ..; done
      - name: Get latest release ID
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/Limit-Theory-Redux/ltheory/releases/tags/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete latest release
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/Limit-Theory-Redux/ltheory/releases/{release_id}
          release_id: ${{ fromJson(steps.get_latest_release.outputs.data).id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete 'latest' tag
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/Limit-Theory-Redux/ltheory/git/refs/tags/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Re-create 'latest' tag with the current SHA
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/Limit-Theory-Redux/ltheory/git/refs
          ref: refs/tags/latest
          sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Latest build"
          body: "Build log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          tag_name: latest
          prerelease: true
          files: ./*.zip
