name: Build Binaries

on:
  pull_request:
  push:
    branches:
      - main

env:
  BUILD_TYPE: RelWithDebInfo

permissions:
  contents: write

jobs:
  build-windows:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Create Build Environment
        run: python configure.py
      - name: Build
        run: python configure.py build
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-win32
          path: ${{github.workspace}}/bin/*

  build-ubuntu:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y libluajit-5.1-dev libglew-dev libsdl2-dev liblz4-dev libfreetype-dev libbullet-dev
      - name: Create Build Environment
        run: python configure.py
      - name: Build
        run: python configure.py build
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: ltheory-bin-ubuntu2004
          path: ${{github.workspace}}/bin/*

  release:
    name: Create release and upload artifacts
    needs:
      - build-windows
      - build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Zip artifacts
        run: for dir in $(ls); do echo zip $dir.zip ./$dir/* -r; done
      - name: Update tag
        run: git tag latest && git push origin latest -f
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          files: ./*.zip
